<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Gounlaf\JanephpBug\Model;

class PatchableEntity
{
    /**
     * @var string|null
     */
    protected $nullableProperty;
    /**
     * @var string|null
     */
    protected $nullableAndRequiredProperty;

    public function getNullableProperty(): ?string
    {
        return $this->nullableProperty;
    }

    public function setNullableProperty(?string $nullableProperty): self
    {
        $this->nullableProperty = $nullableProperty;

        return $this;
    }

    public function getNullableAndRequiredProperty(): ?string
    {
        return $this->nullableAndRequiredProperty;
    }

    public function setNullableAndRequiredProperty(?string $nullableAndRequiredProperty): self
    {
        $this->nullableAndRequiredProperty = $nullableAndRequiredProperty;

        return $this;
    }
}
